{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap"},"topicSections":[{"identifiers":["doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/Option"],"title":"Classes"},{"title":"Structures","identifiers":["doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/LDFunction","doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/LDObject","doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/LDStatic"]},{"title":"Initializers","identifiers":["doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/init(frame:configuration:)"]},{"identifiers":["doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/apiKey","doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/isInspectable","doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/options","doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/server"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/call(method:args:)","doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/call(method:args:completionHandler:)","doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/clearCache()","doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/ldfunction(_:)","doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/ldobject(_:with:)","doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/ldstatic(_:with:)","doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/objectCall(ldobject:method:args:)","doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/preCacheTiles(x:y:zoom:progress:)","doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/render()","doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/userContentController(_:didReceive:)","doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/webView(_:decidePolicyFor:decisionHandler:)"]}],"variants":[{"paths":["\/documentation\/longdomapframework\/longdomap"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/longdomapframework\/longdomap"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework"]]},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LongdoMap"}],"roleHeading":"Class","modules":[{"name":"LongdoMapFramework"}],"externalID":"c:@M@LongdoMapFramework@objc(cs)LongdoMap","symbolKind":"class","role":"symbol","navigatorTitle":[{"text":"LongdoMap","kind":"identifier"}],"title":"LongdoMap"},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.longdo.map.sdk\/objc(cs)WKWebView"],"type":"inheritsFrom"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.longdo.map.sdk\/objc(pl)NSTouchBarProvider","doc:\/\/com.longdo.map.sdk\/objc(pl)NSCoding","doc:\/\/com.longdo.map.sdk\/objc(pl)NSObject","doc:\/\/com.longdo.map.sdk\/objc(pl)CALayerDelegate","doc:\/\/com.longdo.map.sdk\/s7CVarArgP","doc:\/\/com.longdo.map.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.longdo.map.sdk\/s23CustomStringConvertibleP","doc:\/\/com.longdo.map.sdk\/SQ","doc:\/\/com.longdo.map.sdk\/SH","doc:\/\/com.longdo.map.sdk\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.longdo.map.sdk\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.longdo.map.sdk\/objc(pl)UIAppearance","doc:\/\/com.longdo.map.sdk\/objc(pl)UIAppearanceContainer","doc:\/\/com.longdo.map.sdk\/objc(pl)UICoordinateSpace","doc:\/\/com.longdo.map.sdk\/objc(pl)UIDynamicItem","doc:\/\/com.longdo.map.sdk\/objc(pl)UIFocusEnvironment","doc:\/\/com.longdo.map.sdk\/objc(pl)UIFocusItem","doc:\/\/com.longdo.map.sdk\/objc(pl)UIFocusItemContainer","doc:\/\/com.longdo.map.sdk\/objc(pl)UILargeContentViewerItem","doc:\/\/com.longdo.map.sdk\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.longdo.map.sdk\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.longdo.map.sdk\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.longdo.map.sdk\/5UIKit23UITraitChangeObservableP","doc:\/\/com.longdo.map.sdk\/objc(pl)UITraitEnvironment","doc:\/\/com.longdo.map.sdk\/objc(pl)UIUserActivityRestoring","doc:\/\/com.longdo.map.sdk\/objc(pl)WKNavigationDelegate","doc:\/\/com.longdo.map.sdk\/objc(pl)WKScriptMessageHandler"]}],"kind":"symbol","abstract":[{"type":"text","text":"Integrated map tiles from Longdo Map to iOS application."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@IBDesignable","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LongdoMap"}],"platforms":["Mac Catalyst"],"languages":["swift"]}]}],"sections":[],"references":{"doc://com.longdo.map.sdk/documentation/LongdoMapFramework/LongdoMap/LDFunction":{"title":"LongdoMap.LDFunction","navigatorTitle":[{"kind":"identifier","text":"LDFunction"}],"url":"\/documentation\/longdomapframework\/longdomap\/ldfunction","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"LDFunction","kind":"identifier"}],"abstract":[{"type":"text","text":"Javascript function to use with some Longdo Map’s method that needs function as parameter and has returned value."}],"type":"topic","identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/LDFunction","role":"symbol"},"https://api.longdo.com/map/doc/react-native.php#objectCall":{"type":"link","title":"Longdo Map object’s method","url":"https:\/\/api.longdo.com\/map\/doc\/react-native.php#objectCall","titleInlineContent":[{"text":"Longdo Map object’s method","type":"text"}],"identifier":"https:\/\/api.longdo.com\/map\/doc\/react-native.php#objectCall"},"doc://com.longdo.map.sdk/objc(pl)WKScriptMessageHandler":{"title":"WKScriptMessageHandler","type":"unresolvable","identifier":"doc:\/\/com.longdo.map.sdk\/objc(pl)WKScriptMessageHandler"},"doc://com.longdo.map.sdk/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable","identifier":"doc:\/\/com.longdo.map.sdk\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.longdo.map.sdk/documentation/LongdoMapFramework/LongdoMap/call(method:args:)":{"title":"call(method:args:)","url":"\/documentation\/longdomapframework\/longdomap\/call(method:args:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"call","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"method"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"args","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?) -> "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?"}],"abstract":[{"text":"Call ","type":"text"},{"type":"reference","identifier":"https:\/\/api.longdo.com\/map\/doc\/react-native.php#call","isActive":true},{"type":"text","text":"."}],"type":"topic","identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/call(method:args:)","role":"symbol"},"doc://com.longdo.map.sdk/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","type":"unresolvable","identifier":"doc:\/\/com.longdo.map.sdk\/objc(pl)UITraitEnvironment"},"doc://com.longdo.map.sdk/documentation/LongdoMapFramework/LongdoMap/apiKey":{"title":"apiKey","url":"\/documentation\/longdomapframework\/longdomap\/apikey","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"apiKey"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"abstract":[{"type":"text","text":"Longdo Map API key."}],"type":"topic","identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/apiKey","role":"symbol"},"doc://com.longdo.map.sdk/objc(pl)NSTouchBarProvider":{"title":"AppKit.NSTouchBarProvider","type":"unresolvable","identifier":"doc:\/\/com.longdo.map.sdk\/objc(pl)NSTouchBarProvider"},"doc://com.longdo.map.sdk/documentation/LongdoMapFramework":{"url":"\/documentation\/longdomapframework","identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework","type":"topic","role":"collection","abstract":[{"type":"text","text":"Integrated map tiles from Longdo Map to iOS application."}],"kind":"symbol","title":"LongdoMapFramework"},"doc://com.longdo.map.sdk/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.longdo.map.sdk\/SQ"},"doc://com.longdo.map.sdk/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","type":"unresolvable","identifier":"doc:\/\/com.longdo.map.sdk\/objc(pl)UILargeContentViewerItem"},"doc://com.longdo.map.sdk/documentation/LongdoMapFramework/LongdoMap/call(method:args:completionHandler:)":{"title":"call(method:args:completionHandler:)","url":"\/documentation\/longdomapframework\/longdomap\/call(method:args:completionhandler:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"call"},{"text":"(","kind":"text"},{"text":"method","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"args","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"Any","kind":"keyword"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"text":": ((","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")) -> "},{"kind":"keyword","text":"Any"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Call "},{"type":"reference","identifier":"https:\/\/api.longdo.com\/map\/doc\/react-native.php#call","isActive":true},{"text":" with callback.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/call(method:args:completionHandler:)","role":"symbol"},"doc://com.longdo.map.sdk/documentation/LongdoMapFramework/LongdoMap/ldfunction(_:)":{"title":"ldfunction(_:)","url":"\/documentation\/longdomapframework\/longdomap\/ldfunction(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"ldfunction","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:18LongdoMapFramework0aB0C10LDFunctionV","text":"LDFunction","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/ldfunction(_:)","type":"topic","abstract":[{"text":"Create LDFunction.","type":"text"}],"role":"symbol"},"doc://com.longdo.map.sdk/objc(pl)NSObject":{"identifier":"doc:\/\/com.longdo.map.sdk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.longdo.map.sdk/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/com.longdo.map.sdk\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions","type":"unresolvable"},"doc://com.longdo.map.sdk/objc(pl)UIFocusItemContainer":{"identifier":"doc:\/\/com.longdo.map.sdk\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer","type":"unresolvable"},"doc://com.longdo.map.sdk/objc(pl)UIFocusItem":{"identifier":"doc:\/\/com.longdo.map.sdk\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem","type":"unresolvable"},"doc://com.longdo.map.sdk/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/com.longdo.map.sdk\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment","type":"unresolvable"},"doc://com.longdo.map.sdk/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/com.longdo.map.sdk\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"https://api.longdo.com/map/doc/react-native.php#object":{"titleInlineContent":[{"text":"Longdo Map’s object","type":"text"}],"url":"https:\/\/api.longdo.com\/map\/doc\/react-native.php#object","title":"Longdo Map’s object","type":"link","identifier":"https:\/\/api.longdo.com\/map\/doc\/react-native.php#object"},"doc://com.longdo.map.sdk/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/com.longdo.map.sdk\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable","type":"unresolvable"},"doc://com.longdo.map.sdk/documentation/LongdoMapFramework/LongdoMap/userContentController(_:didReceive:)":{"title":"userContentController(_:didReceive:)","url":"\/documentation\/longdomapframework\/longdomap\/usercontentcontroller(_:didreceive:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userContentController"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)WKUserContentController","kind":"typeIdentifier","text":"WKUserContentController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKScriptMessage","preciseIdentifier":"c:objc(cs)WKScriptMessage"},{"text":")","kind":"text"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/userContentController(_:didReceive:)","role":"symbol"},"doc://com.longdo.map.sdk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.longdo.map.sdk\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.longdo.map.sdk/SH":{"identifier":"doc:\/\/com.longdo.map.sdk\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.longdo.map.sdk/documentation/LongdoMapFramework/LongdoMap/objectCall(ldobject:method:args:)":{"title":"objectCall(ldobject:method:args:)","url":"\/documentation\/longdomapframework\/longdomap\/objectcall(ldobject:method:args:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"objectCall"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ldobject"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:18LongdoMapFramework0aB0C8LDObjectV","text":"LDObject","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"method","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"args"},{"kind":"text","text":": ["},{"text":"Any","kind":"keyword"},{"text":"]?) -> ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/objectCall(ldobject:method:args:)","type":"topic","abstract":[{"text":"Call ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/api.longdo.com\/map\/doc\/react-native.php#objectCall"},{"type":"text","text":"."}],"role":"symbol"},"doc://com.longdo.map.sdk/objc(pl)CALayerDelegate":{"type":"unresolvable","identifier":"doc:\/\/com.longdo.map.sdk\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate"},"doc://com.longdo.map.sdk/documentation/LongdoMapFramework/LongdoMap/clearCache()":{"title":"clearCache()","url":"\/documentation\/longdomapframework\/longdomap\/clearcache()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"clearCache","kind":"identifier"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/clearCache()","type":"topic","abstract":[],"role":"symbol"},"doc://com.longdo.map.sdk/documentation/LongdoMapFramework/LongdoMap/ldstatic(_:with:)":{"title":"ldstatic(_:with:)","url":"\/documentation\/longdomapframework\/longdomap\/ldstatic(_:with:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"ldstatic","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:18LongdoMapFramework0aB0C8LDStaticV","kind":"typeIdentifier","text":"LDStatic"}],"abstract":[{"type":"text","text":"Create "},{"identifier":"https:\/\/api.longdo.com\/map\/doc\/react-native.php#static","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"topic","identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/ldstatic(_:with:)","role":"symbol"},"doc://com.longdo.map.sdk/objc(pl)WKNavigationDelegate":{"title":"WKNavigationDelegate","type":"unresolvable","identifier":"doc:\/\/com.longdo.map.sdk\/objc(pl)WKNavigationDelegate"},"doc://com.longdo.map.sdk/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","type":"unresolvable","identifier":"doc:\/\/com.longdo.map.sdk\/objc(pl)UIAccessibilityIdentification"},"doc://com.longdo.map.sdk/documentation/LongdoMapFramework/LongdoMap/Option":{"abstract":[{"text":"Setting class for Longdo Map.","type":"text"}],"navigatorTitle":[{"text":"Option","kind":"identifier"}],"identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/Option","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Option","kind":"identifier"}],"role":"symbol","title":"LongdoMap.Option","kind":"symbol","url":"\/documentation\/longdomapframework\/longdomap\/option","type":"topic"},"doc://com.longdo.map.sdk/documentation/LongdoMapFramework/LongdoMap/isInspectable":{"title":"isInspectable","url":"\/documentation\/longdomapframework\/longdomap\/isinspectable","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isInspectable"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/isInspectable","type":"topic","abstract":[],"role":"symbol"},"doc://com.longdo.map.sdk/documentation/LongdoMapFramework/LongdoMap/render()":{"title":"render()","url":"\/documentation\/longdomapframework\/longdomap\/render()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"render","kind":"identifier"},{"kind":"text","text":"()"}],"abstract":[{"text":"Rendered Longdo Map view.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/render()","role":"symbol"},"doc://com.longdo.map.sdk/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/com.longdo.map.sdk\/objc(pl)NSCoding"},"doc://com.longdo.map.sdk/documentation/LongdoMapFramework/LongdoMap/preCacheTiles(x:y:zoom:progress:)":{"title":"preCacheTiles(x:y:zoom:progress:)","url":"\/documentation\/longdomapframework\/longdomap\/precachetiles(x:y:zoom:progress:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"preCacheTiles","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"x"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ClosedRange","preciseIdentifier":"s:SN"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":">, "},{"text":"y","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SN","text":"ClosedRange","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"zoom"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"progress"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"percent"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/preCacheTiles(x:y:zoom:progress:)","role":"symbol"},"https://api.longdo.com/map/doc/react-native.php#call":{"type":"link","title":"Longdo Map’s method","url":"https:\/\/api.longdo.com\/map\/doc\/react-native.php#call","titleInlineContent":[{"type":"text","text":"Longdo Map’s method"}],"identifier":"https:\/\/api.longdo.com\/map\/doc\/react-native.php#call"},"doc://com.longdo.map.sdk/objc(pl)UICoordinateSpace":{"type":"unresolvable","identifier":"doc:\/\/com.longdo.map.sdk\/objc(pl)UICoordinateSpace","title":"UIKit.UICoordinateSpace"},"doc://com.longdo.map.sdk/documentation/LongdoMapFramework/LongdoMap/init(frame:configuration:)":{"type":"topic","role":"symbol","url":"\/documentation\/longdomapframework\/longdomap\/init(frame:configuration:)","abstract":[{"text":"Creates Longdo Map view and initializes it with the specified frame.","type":"text"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"frame"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"text":"WKWebViewConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebViewConfiguration"},{"kind":"text","text":")"}],"title":"init(frame:configuration:)","identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/init(frame:configuration:)","kind":"symbol"},"doc://com.longdo.map.sdk/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/com.longdo.map.sdk\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://com.longdo.map.sdk/objc(pl)UIAppearance":{"type":"unresolvable","identifier":"doc:\/\/com.longdo.map.sdk\/objc(pl)UIAppearance","title":"UIKit.UIAppearance"},"doc://com.longdo.map.sdk/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.longdo.map.sdk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.longdo.map.sdk/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/com.longdo.map.sdk\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://com.longdo.map.sdk/documentation/LongdoMapFramework/LongdoMap/webView(_:decidePolicyFor:decisionHandler:)":{"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/longdomapframework\/longdomap\/webview(_:decidepolicyfor:decisionhandler:)","role":"symbol","identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/webView(_:decidePolicyFor:decisionHandler:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"webView","kind":"identifier"},{"kind":"text","text":"("},{"text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"decidePolicyFor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKNavigationAction","kind":"typeIdentifier","text":"WKNavigationAction"},{"text":", ","kind":"text"},{"text":"decisionHandler","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"WKNavigationActionPolicy","preciseIdentifier":"c:@E@WKNavigationActionPolicy"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"webView(_:decidePolicyFor:decisionHandler:)"},"doc://com.longdo.map.sdk/objc(pl)UIDynamicItem":{"type":"unresolvable","identifier":"doc:\/\/com.longdo.map.sdk\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem"},"doc://com.longdo.map.sdk/objc(cs)WKWebView":{"type":"unresolvable","identifier":"doc:\/\/com.longdo.map.sdk\/objc(cs)WKWebView","title":"WKWebView"},"doc://com.longdo.map.sdk/documentation/LongdoMapFramework/LongdoMap/options":{"title":"options","url":"\/documentation\/longdomapframework\/longdomap\/options","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"options","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"LongdoMap","preciseIdentifier":"c:@M@LongdoMapFramework@objc(cs)LongdoMap"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18LongdoMapFramework0aB0C6OptionC","text":"Option"}],"identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/options","type":"topic","abstract":[{"type":"text","text":"Initial Longdo Map setting."}],"role":"symbol"},"doc://com.longdo.map.sdk/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","identifier":"doc:\/\/com.longdo.map.sdk\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://com.longdo.map.sdk/documentation/LongdoMapFramework/LongdoMap/ldobject(_:with:)":{"title":"ldobject(_:with:)","url":"\/documentation\/longdomapframework\/longdomap\/ldobject(_:with:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"ldobject","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": [","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"LDObject","preciseIdentifier":"s:18LongdoMapFramework0aB0C8LDObjectV"}],"identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/ldobject(_:with:)","type":"topic","abstract":[{"type":"text","text":"Create "},{"type":"reference","identifier":"https:\/\/api.longdo.com\/map\/doc\/react-native.php#object","isActive":true},{"type":"text","text":"."}],"role":"symbol"},"https://api.longdo.com/map/doc/react-native.php#static":{"titleInlineContent":[{"type":"text","text":"Longdo Map’s static object"}],"url":"https:\/\/api.longdo.com\/map\/doc\/react-native.php#static","title":"Longdo Map’s static object","type":"link","identifier":"https:\/\/api.longdo.com\/map\/doc\/react-native.php#static"},"doc://com.longdo.map.sdk/documentation/LongdoMapFramework/LongdoMap/server":{"url":"\/documentation\/longdomapframework\/longdomap\/server","identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/server","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Longdo Map server URL."}],"kind":"symbol","title":"server","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"server"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://com.longdo.map.sdk/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.longdo.map.sdk\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.longdo.map.sdk/documentation/LongdoMapFramework/LongdoMap/LDStatic":{"title":"LongdoMap.LDStatic","navigatorTitle":[{"kind":"identifier","text":"LDStatic"}],"url":"\/documentation\/longdomapframework\/longdomap\/ldstatic","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LDStatic"}],"abstract":[{"type":"text","text":"Longdo Map’s static object."}],"type":"topic","identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/LDStatic","role":"symbol"},"doc://com.longdo.map.sdk/documentation/LongdoMapFramework/LongdoMap/LDObject":{"title":"LongdoMap.LDObject","navigatorTitle":[{"kind":"identifier","text":"LDObject"}],"url":"\/documentation\/longdomapframework\/longdomap\/ldobject","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"LDObject","kind":"identifier"}],"identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/LDObject","type":"topic","abstract":[{"type":"text","text":"Longdo Map’s object."}],"role":"symbol"},"doc://com.longdo.map.sdk/documentation/LongdoMapFramework/LongdoMap":{"url":"\/documentation\/longdomapframework\/longdomap","identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Integrated map tiles from Longdo Map to iOS application."}],"navigatorTitle":[{"kind":"identifier","text":"LongdoMap"}],"title":"LongdoMap","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LongdoMap"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.longdo.map.sdk\/objc(cs)WKWebView"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.longdo.map.sdk\/objc(pl)WKNavigationDelegate","doc:\/\/com.longdo.map.sdk\/objc(pl)WKScriptMessageHandler"]}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"LongdoMap","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"WKWebView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"}]}]}