{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Initializer","symbolKind":"init","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"text":", ","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKWebViewConfiguration","kind":"typeIdentifier","text":"WKWebViewConfiguration"},{"kind":"text","text":")"}],"title":"init(frame:configuration:)","modules":[{"name":"LongdoMapFramework"}],"externalID":"c:@M@LongdoMapFramework@objc(cs)LongdoMap(im)initWithFrame:configuration:"},"abstract":[{"text":"Creates Longdo Map view and initializes it with the specified frame.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/longdomapframework\/longdomap\/init(frame:configuration:)"]},{"paths":["\/documentation\/longdomapframework\/longdomap\/init(frame:configuration:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/init(frame:configuration:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework","doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":", "},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebViewConfiguration","text":"WKWebViewConfiguration"},{"text":")","kind":"text"}],"platforms":["Mac Catalyst"]}]}],"references":{"doc://com.longdo.map.sdk/documentation/LongdoMapFramework/LongdoMap/init(frame:configuration:)":{"type":"topic","role":"symbol","url":"\/documentation\/longdomapframework\/longdomap\/init(frame:configuration:)","abstract":[{"text":"Creates Longdo Map view and initializes it with the specified frame.","type":"text"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"frame"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"text":"WKWebViewConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebViewConfiguration"},{"kind":"text","text":")"}],"title":"init(frame:configuration:)","identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/init(frame:configuration:)","kind":"symbol"},"doc://com.longdo.map.sdk/documentation/LongdoMapFramework":{"url":"\/documentation\/longdomapframework","identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework","type":"topic","role":"collection","abstract":[{"type":"text","text":"Integrated map tiles from Longdo Map to iOS application."}],"kind":"symbol","title":"LongdoMapFramework"},"doc://com.longdo.map.sdk/documentation/LongdoMapFramework/LongdoMap":{"url":"\/documentation\/longdomapframework\/longdomap","identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Integrated map tiles from Longdo Map to iOS application."}],"navigatorTitle":[{"kind":"identifier","text":"LongdoMap"}],"title":"LongdoMap","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LongdoMap"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithFrame:"},{"text":"(","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") "},{"text":"frame","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configuration:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)WKWebViewConfiguration","text":"WKWebViewConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"configuration"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}