{"identifier":{"url":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/isInspectable","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInspectable"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["Mac Catalyst"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework","doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@LongdoMapFramework@objc(cs)LongdoMap(py)inspectable","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInspectable"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"isInspectable","role":"symbol","modules":[{"name":"LongdoMapFramework"}],"symbolKind":"property","roleHeading":"Instance Property"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/longdomapframework\/longdomap\/isinspectable"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/longdomapframework\/longdomap\/isinspectable"]}],"references":{"doc://com.longdo.map.sdk/documentation/LongdoMapFramework":{"url":"\/documentation\/longdomapframework","identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework","type":"topic","role":"collection","abstract":[{"type":"text","text":"Integrated map tiles from Longdo Map to iOS application."}],"kind":"symbol","title":"LongdoMapFramework"},"doc://com.longdo.map.sdk/documentation/LongdoMapFramework/LongdoMap/isInspectable":{"title":"isInspectable","url":"\/documentation\/longdomapframework\/longdomap\/isinspectable","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isInspectable"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/isInspectable","type":"topic","abstract":[],"role":"symbol"},"doc://com.longdo.map.sdk/documentation/LongdoMapFramework/LongdoMap":{"url":"\/documentation\/longdomapframework\/longdomap","identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Integrated map tiles from Longdo Map to iOS application."}],"navigatorTitle":[{"kind":"identifier","text":"LongdoMap"}],"title":"LongdoMap","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LongdoMap"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"getter","kind":"keyword"},{"text":"=","kind":"text"},{"text":"isInspectable","kind":"identifier"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"text":"inspectable","kind":"identifier"},{"text":";","kind":"text"}]}]}}]}]}