{"hierarchy":{"paths":[["doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework","doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap"]]},"sections":[],"variants":[{"paths":["\/documentation\/longdomapframework\/longdomap\/usercontentcontroller(_:didreceive:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/longdomapframework\/longdomap\/usercontentcontroller(_:didreceive:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/userContentController(_:didReceive:)"},"metadata":{"externalID":"c:@M@LongdoMapFramework@objc(cs)LongdoMap(im)userContentController:didReceiveScriptMessage:","modules":[{"name":"LongdoMapFramework"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"userContentController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WKUserContentController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKUserContentController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKScriptMessage","preciseIdentifier":"c:objc(cs)WKScriptMessage"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","title":"userContentController(_:didReceive:)","symbolKind":"method","role":"symbol"},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"WKScriptMessageHandler.userContentController(_:didReceive:)"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["Mac Catalyst"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userContentController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"userContentController"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKUserContentController","text":"WKUserContentController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":" "},{"text":"message","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)WKScriptMessage","kind":"typeIdentifier","text":"WKScriptMessage"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"references":{"doc://com.longdo.map.sdk/documentation/LongdoMapFramework":{"url":"\/documentation\/longdomapframework","identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework","type":"topic","role":"collection","abstract":[{"type":"text","text":"Integrated map tiles from Longdo Map to iOS application."}],"kind":"symbol","title":"LongdoMapFramework"},"doc://com.longdo.map.sdk/documentation/LongdoMapFramework/LongdoMap":{"url":"\/documentation\/longdomapframework\/longdomap","identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Integrated map tiles from Longdo Map to iOS application."}],"navigatorTitle":[{"kind":"identifier","text":"LongdoMap"}],"title":"LongdoMap","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LongdoMap"}]},"doc://com.longdo.map.sdk/documentation/LongdoMapFramework/LongdoMap/userContentController(_:didReceive:)":{"title":"userContentController(_:didReceive:)","url":"\/documentation\/longdomapframework\/longdomap\/usercontentcontroller(_:didreceive:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userContentController"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)WKUserContentController","kind":"typeIdentifier","text":"WKUserContentController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKScriptMessage","preciseIdentifier":"c:objc(cs)WKScriptMessage"},{"text":")","kind":"text"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/userContentController(_:didReceive:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"userContentController:"},{"kind":"text","text":"("},{"text":"WKUserContentController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKUserContentController"},{"kind":"text","text":" *) "},{"text":"userContentController","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveScriptMessage:"},{"kind":"text","text":"("},{"text":"WKScriptMessage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKScriptMessage"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"message"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"}]}]}