{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"webView","kind":"internalParam"},{"kind":"text","text":": "},{"text":"WKWebView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView"},{"text":", ","kind":"text"},{"text":"decidePolicyFor","kind":"externalParam"},{"kind":"text","text":" "},{"text":"navigationAction","kind":"internalParam"},{"kind":"text","text":": "},{"text":"WKNavigationAction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKNavigationAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"decisionHandler"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"text":" (","kind":"text"},{"preciseIdentifier":"c:@E@WKNavigationActionPolicy","kind":"typeIdentifier","text":"WKNavigationActionPolicy"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"webView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"decidePolicyFor"},{"kind":"text","text":": "},{"text":"WKNavigationAction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKNavigationAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"decisionHandler"},{"text":": (","kind":"text"},{"text":"WKNavigationActionPolicy","kind":"typeIdentifier","preciseIdentifier":"c:@E@WKNavigationActionPolicy"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"title":"webView(_:decidePolicyFor:decisionHandler:)","roleHeading":"Instance Method","externalID":"c:@M@LongdoMapFramework@objc(cs)LongdoMap(im)webView:decidePolicyForNavigationAction:decisionHandler:","role":"symbol","navigatorTitle":[{"text":"webView:decidePolicyForNavigationAction:decisionHandler:","kind":"identifier"}],"modules":[{"name":"LongdoMapFramework"}],"symbolKind":"method"},"kind":"symbol","sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"WKNavigationDelegate.webView(_:decidePolicyFor:decisionHandler:)","type":"codeVoice"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework","doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap"]]},"variants":[{"paths":["\/documentation\/longdomapframework\/longdomap\/webview(_:decidepolicyfor:decisionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/longdomapframework\/longdomap\/webview(_:decidepolicyfor:decisionhandler:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/webView(_:decidePolicyFor:decisionHandler:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.longdo.map.sdk/documentation/LongdoMapFramework/LongdoMap":{"identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LongdoMap"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LongdoMap"}],"title":"LongdoMap","kind":"symbol","url":"\/documentation\/longdomapframework\/longdomap","abstract":[{"type":"text","text":"Integrated map tiles from Longdo Map to iOS application."}]},"doc://com.longdo.map.sdk/documentation/LongdoMapFramework":{"role":"collection","type":"topic","identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework","kind":"symbol","title":"LongdoMapFramework","url":"\/documentation\/longdomapframework","abstract":[{"text":"Integrated map tiles from Longdo Map to iOS application.","type":"text"}]},"doc://com.longdo.map.sdk/documentation/LongdoMapFramework/LongdoMap/webView(_:decidePolicyFor:decisionHandler:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"decidePolicyFor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKNavigationAction","kind":"typeIdentifier","text":"WKNavigationAction"},{"text":", ","kind":"text"},{"text":"decisionHandler","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"WKNavigationActionPolicy","kind":"typeIdentifier","preciseIdentifier":"c:@E@WKNavigationActionPolicy"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"webView(_:decidePolicyFor:decisionHandler:)","type":"topic","url":"\/documentation\/longdomapframework\/longdomap\/webview(_:decidepolicyfor:decisionhandler:)","navigatorTitle":[{"kind":"identifier","text":"webView:decidePolicyForNavigationAction:decisionHandler:"}],"kind":"symbol","identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap\/webView(_:decidePolicyFor:decisionHandler:)","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"webView:decidePolicyForNavigationAction:decisionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"webView:decidePolicyForNavigationAction:decisionHandler:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"webView:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"text":" *) ","kind":"text"},{"text":"webView","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"decidePolicyForNavigationAction:"},{"kind":"text","text":"("},{"text":"WKNavigationAction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKNavigationAction"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"navigationAction"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decisionHandler:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"preciseIdentifier":"c:@E@WKNavigationActionPolicy","text":"WKNavigationActionPolicy","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"text":"decisionHandler","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.longdo.map.sdk~1documentation~1LongdoMapFramework~1LongdoMap\/title","op":"replace","value":"LongdoMap"},{"value":[{"text":"LongdoMap","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.longdo.map.sdk~1documentation~1LongdoMapFramework~1LongdoMap\/fragments"},{"path":"\/references\/doc:~1~1com.longdo.map.sdk~1documentation~1LongdoMapFramework~1LongdoMap~1webView(_:decidePolicyFor:decisionHandler:)\/title","op":"replace","value":"webView:decidePolicyForNavigationAction:decisionHandler:"},{"path":"\/references\/doc:~1~1com.longdo.map.sdk~1documentation~1LongdoMapFramework~1LongdoMap~1webView(_:decidePolicyFor:decisionHandler:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"webView:decidePolicyForNavigationAction:decisionHandler:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}