{"topicSections":[{"identifiers":["doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap"],"title":"Classes"},{"title":"Enumerations","identifiers":["doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoLocale","doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoTurn"]}],"primaryContentSections":[{"content":[{"level":2,"anchor":"Overview","type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The Framework use map resources from Longdo.COM services yet allow developers to use other map tile standards such as TMS, WMS, and WMTS. The Framework provides most must have features allow developers to show markers on the map with a few lines. It also includes exclusive services such as POI tags, traffic events, and traffic camera."}]}],"kind":"content"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/longdomapframework"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/longdomapframework"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework"},"sections":[],"metadata":{"role":"collection","modules":[{"name":"LongdoMapFramework"}],"title":"LongdoMapFramework","externalID":"LongdoMapFramework","symbolKind":"module","roleHeading":"Framework"},"kind":"symbol","hierarchy":{"paths":[[]]},"abstract":[{"type":"text","text":"Integrated map tiles from Longdo Map to iOS application."}],"references":{"doc://com.longdo.map.sdk/documentation/LongdoMapFramework/LongdoMapFrameworkVersionNumber":{"url":"\/documentation\/longdomapframework\/longdomapframeworkversionnumber","type":"topic","abstract":[{"text":"Project version number for LongdoMapFramework.","type":"text"}],"fragments":[{"kind":"identifier","text":"LongdoMapFrameworkVersionNumber"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMapFrameworkVersionNumber","title":"LongdoMapFrameworkVersionNumber"},"doc://com.longdo.map.sdk/documentation/LongdoMapFramework/LongdoTurn":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LongdoTurn"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"LongdoTurn"}],"url":"\/documentation\/longdomapframework\/longdoturn","kind":"symbol","identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoTurn","title":"LongdoTurn","abstract":[{"text":"Route Turn enumeration.","type":"text"}]},"doc://com.longdo.map.sdk/documentation/LongdoMapFramework":{"abstract":[{"type":"text","text":"Integrated map tiles from Longdo Map to iOS application."}],"title":"LongdoMapFramework","identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/longdomapframework"},"doc://com.longdo.map.sdk/documentation/LongdoMapFramework/LongdoLocale":{"url":"\/documentation\/longdomapframework\/longdolocale","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LongdoLocale"}],"navigatorTitle":[{"text":"LongdoLocale","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoLocale","title":"LongdoLocale","role":"symbol","abstract":[{"type":"text","text":"Locale enumeration."}]},"doc://com.longdo.map.sdk/documentation/LongdoMapFramework/LongdoMap":{"title":"LongdoMap","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LongdoMap","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap","kind":"symbol","url":"\/documentation\/longdomapframework\/longdomap","navigatorTitle":[{"kind":"identifier","text":"LongdoMap"}],"abstract":[{"text":"Integrated map tiles from Longdo Map to iOS application.","type":"text"}]},"doc://com.longdo.map.sdk/documentation/LongdoMapFramework/LongdoMapFrameworkVersionString":{"kind":"symbol","role":"symbol","url":"\/documentation\/longdomapframework\/longdomapframeworkversionstring","identifier":"doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMapFrameworkVersionString","fragments":[{"kind":"identifier","text":"LongdoMapFrameworkVersionString"}],"abstract":[{"text":"Project version string for LongdoMapFramework.","type":"text"}],"type":"topic","title":"LongdoMapFrameworkVersionString"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMap"]},{"title":"Variables","identifiers":["doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMapFrameworkVersionNumber","doc:\/\/com.longdo.map.sdk\/documentation\/LongdoMapFramework\/LongdoMapFrameworkVersionString"]}],"op":"replace"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/references\/doc:~1~1com.longdo.map.sdk~1documentation~1LongdoMapFramework~1LongdoMap\/title","op":"replace","value":"LongdoMap"},{"value":[{"text":"LongdoMap","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.longdo.map.sdk~1documentation~1LongdoMapFramework~1LongdoMap\/fragments"}]}]}